services:
  - type: web
    name: phronesis-backend
    runtime: node
    repo: https://github.com/gtechglobal-dev/phronesis-result-checker
    plan: free
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npx prisma db push && npm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true

  - type: static
    name: phronesis-frontend
    repo: https://github.com/gtechglobal-dev/phronesis-result-checker
    plan: free
    region: oregon
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          name: phronesis-backend
          type: web
          property: url
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
