services:
  - type: web
    name: phronesis-backend
    runtime: node
    repo: https://github.com/gtechglobal-dev/phronesis-result-checker
    plan: free
    region: oregon
    rootDir: .
    buildCommand: cd backend && npm ci && cd ../frontend && npm install && npm run build
    startCommand: cd backend && node src/index.js
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: https://phronesisresultportal.onrender.com
      - key: ADMIN_USERNAMES
        value: Admin1,Admin2,Admin3
      - key: ADMIN_PASSWORD
        sync: false
      - key: SUBJECT_TEACHER_PASSWORD
        sync: false
